TOPLEVEL_LANG = verilog
VERILOG_SOURCES = ../src/tt_um_fsm_top.v ../src/top_module.v ../src/arranque_rampa_parcial.v ../src/prescaler_clk.v

TOPLEVEL = tt_um_fsm_top
MODULE = test_user_module

include $(shell cocotb-config --makefiles)/Makefile.inc
